# Configuration for Murata 1SC EVK Low Powered Tracker Demo
# All values can be overridden by command line parameters

# Serial port for the modem (Windows example: COM3, Linux example: /dev/ttyUSB0)
port: COM9

# Server in the format host:port
server: udp-eu.tartabit.com:10106

location:
  # simulated, cellid
  type: simulated
  lat: 45.448803450183924
  lon: -75.63533774831912

# Reporting interval in seconds
interval: 120

# Reading interval in seconds (sensor sampling)
readings: 60

# Optional: Override IMEI (otherwise read from modem)
imei: 

# Customer code (8 hex digits)
code: "00000000"

# Packet data APN, uncomment the APN for your SIM card or set your own.
# Telenor Connexion
apn: connect.cxn
# 1NCE
#apn: iot.1nce.net
